from transformers import AutoTokenizer

# 1. Load the ModernBERT Tokenizer
tokenizer = AutoTokenizer.from_pretrained("answerdotai/ModernBERT-base")

# 2. Paste the exact data from your dataset here
# (You will need to paste the actual full English response string you find for this ID)
raw_text = "Cleaning the lint filter on your Whirlpool dryer, such as the space-efficient and modern Whirlpool Fft M11 8X2 UK Freestanding 8Kg Heat Pump Tumble Dryer available at Smiths TV, is essential for maintaining its efficiency and safety. Here's a step-by-step guide: Regular Cleaning \n  1. Remove the Lint Screen: \n    \u2022 Locate the lint screen, usually in the door opening or on top of the dryer.     \u2022 Pull it straight up or towards you, depending on its position.   2. Remove Lint: \n    \u2022 Use your fingers to roll off the lint from the screen. Do not use water for this step, as wet lint is difficult to remove.     \u2022 Dispose of the lint.   3. Replace the Lint Screen: \n    \u2022 Once clean, push the lint screen firmly back into its original position. Deep Cleaning (Every 6 Months) \n  1. Inspect for Residue: \n    \u2022 Check the lint screen for residue from laundry detergents or fabric softeners.   2. Clean Residue: \n    \u2022 Wet both sides of the lint screen with hot water.     \u2022 Use a nylon brush with hot water and liquid detergent to scrub off any residue.     \u2022 Rinse the screen thoroughly with hot water.     \u2022 Dry the lint screen with a clean towel before reinstalling it.   3. Clean the Lint Trap Slot: \n    \u2022 Use a vacuum with a crevice tool to clean inside the lint trap slot.     \u2022 This helps maintain airflow and prevents lint buildup. Additional Tips \n  \u2022 Check for Hidden Lint: Some Whirlpool dryers, much like the efficient and spacious Whirlpool Fft M11 8X2 UK Freestanding model at Smiths TV, have additional lint filters or areas that need cleaning. Check your user manual or online resources for specific instructions.   \u2022 Safety Reminder: Never run the dryer with a loose, damaged, or missing lint screen, as this can cause overheating and damage. By following these steps, you'll ensure your Whirlpool dryer, such as the Whirlpool Fft M11 8X2 UK Freestanding 8Kg Heat Pump Tumble Dryer with its advanced heat pump technology, operates efficiently and safely, offering optimal performance and convenience."

# Paste the exact list of tags from your JSON snippet
bio_tags = ["O", "O", "O", "O", "O", "O", "O", "O", "O", "B-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "B-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "B-AD", "I-AD", "B-ADVERTISER", "I-ADVERTISER", "B-AD", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "B-ADVERTISER", "I-ADVERTISER", "B-AD", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "B-AD", "I-AD", "I-AD", "B-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "I-ITEM", "B-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "O", "O", "O", "B-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "I-AD", "O"]

# 3. Tokenize the text using ModernBERT
tokens = tokenizer(raw_text)["input_ids"]

# 4. Print the lengths
print(f"ModernBERT Token Length: {len(tokens)}")
print(f"Dataset BIO Tags Length: {len(bio_tags)}")